#!/bin/bash

#SBATCH -J TRANS_Chemistry
#SBATCH -A r00408
#SBATCH -o /N/u/shahrob/Carbonate/Research/Scripts/Domain/Chemistry/output/TRANS_Chemistry_%j.out
#SBATCH -e /N/u/shahrob/Carbonate/Research/Scripts/Domain/Chemistry/error/TRANS_Chemistry_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=shahrob@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=04:00:00
#SBATCH --mem=4G

# Load any modules that your program needs

# Activate your Python environment if necessary
source activate env

# Run your Python script
python transform.py
